# Auto-generated by bin/build_brew.sh.
# Runs an exact published ArchiveBox wheel through uv's normal tool path.

class Archivebox < Formula
  desc "Self-hosted internet archiving solution"
  homepage "https://archivebox.io"
  url "https://files.pythonhosted.org/packages/b3/20/d035db771b4fc6bb65af30f113afd011e93203a6381831741693de867fbb/archivebox-0.9.35rc415-py3-none-any.whl"
  version "0.9.35rc415"
  sha256 "d747d200e67d7b190e54b52772e49f9656b05a6c910aacb197261de02818d461"
  license "MIT"

  bottle do
    root_url "https://raw.githubusercontent.com/ArchiveBox/homebrew-archivebox/main/Bottles"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "794aca6788c3660acd4af9caa1037c7fe10b17598412d5b8ed936aae5214db89"
  end

  depends_on "uv"

  def install
    (bin/"archivebox").write <<~SH
      #!/bin/sh
      exec "#{formula_opt_bin("uv")}/uv" tool run --from "https://files.pythonhosted.org/packages/b3/20/d035db771b4fc6bb65af30f113afd011e93203a6381831741693de867fbb/archivebox-0.9.35rc415-py3-none-any.whl" archivebox "$@"
    SH
    chmod 0755, bin/"archivebox"
  end

  def caveats
    <<~EOS
      ArchiveBox 0.9.35rc415 runs from its verified PyPI wheel through uv.

      To create a collection and install runtime extractors:
        mkdir -p ~/archivebox/data
        cd ~/archivebox/data
        archivebox init
        archivebox install
    EOS
  end

  test do
    (testpath/"data").mkpath
    cd testpath/"data" do
      system "#{bin}/archivebox", "init"
      assert_match "0.9.35rc415", shell_output("#{bin}/archivebox version")
      system "#{bin}/archivebox", "status"
    end
  end
end
