# Auto-generated by bin/build_brew.sh.
# Tracks ArchiveBox/ArchiveBox@dev without vendoring Python dependency resources.

class Archivebox < Formula
  desc "Self-hosted internet archiving solution"
  homepage "https://archivebox.io"
  url "https://github.com/ArchiveBox/ArchiveBox.git",
      revision: "8367578f9b7f04a3f75289442c5b0b946c3a1358"
  version "0.9.34rc55.20260604150025"
  license "MIT"
  head "https://github.com/ArchiveBox/ArchiveBox.git", branch: "dev"

  depends_on "python@3.13"

  def install
    venv = libexec/"venv"
    python = Formula["python@3.13"].opt_bin/"python3.13"

    system python, "-m", "venv", venv
    system venv/"bin/python", "-m", "pip", "install", "--upgrade", "pip", "setuptools", "wheel"
    system venv/"bin/python", "-m", "pip", "install", "--no-binary", "cbor2", "."

    bin.install_symlink venv/"bin/archivebox"
  end

  def caveats
    <<~EOS
      ArchiveBox is installed from ArchiveBox/ArchiveBox@dev:
        8367578f9b7f04a3f75289442c5b0b946c3a1358

      To create a collection and install runtime extractors:
        mkdir -p ~/archivebox/data
        cd ~/archivebox/data
        archivebox init
        archivebox install
    EOS
  end

  test do
    assert_match "0.9.34rc55", shell_output("#{bin}/archivebox version")
  end
end
